python gmm.py \
  --model_name Qwen/Qwen2.5-Coder-1.5B \
  --output_dir ./router_gmm_ckpt \
  --batch_size 16 \
  --train_k 5000 \
  --eval_k 1000 \
  --routing_dim 128 \
  --gmm_components 8 \
  --feature_layers 4 \
  --eval_split test \
  --force_recompute_features